### ISSUE TITLE
一些使用问题

### ISSUE THREAD

**Issue by xygengcn** [huturen/http-request-mock#11]
1、typescript使用：很多类型都没export出来，建议都export到主入口

2、有没有hook可以正常请求，然后可以对请求结果进行修改

**Comment by huturen** [comment]
`1、typescript使用：很多类型都没export出来，建议都export到主入口`
你希望，把哪些类型export出来，我看下你的诉求，考虑下，看要把哪些类型放出来

`2、有没有hook可以正常请求，然后可以对请求结果进行修改`
有的。

-  A. 如果你使用命令行整合工具，可以参考这个[例子](https://huturen.github.io/http-request-mock-docs/feature/remote/#mock-data-file):
![image](https://user-images.githubusercontent.com/5173298/204513421-73d9d120-49b4-458d-9750-62dbf858b3f8.png)

- B. 如果你直接使用mock函数，参下面的例子：
![image](https://user-images.githubusercontent.com/5173298/204513750-bdbb1f1a-b9b6-4ebc-aa86-b0e807d65f0e.png)

```javascript
mocker.mock({ 
  url: 'https://www.api.com/some/path', 
  // 指定remote属性，请求 https://www.api.com/some/path 时，
  // 实际会以请求  https://jsonplaceholder.typicode.com/todos/1 的返回结果做为返回
  // 然后在 response 里面做定制（注意指定的remote地址，必须遵循跨域规范）
  remote: 'https://jsonplaceholder.typicode.com/todos/1',
  delay: 300, 
  response(remote) {
    const remoteData = remote.responseJson
    remoteData.customizedMsg = 'by mock';
    return remoteData
  }
});
```

**Comment by xygengcn** [comment]
1: 类似：MockItemInfo,HttpVerb,MockItem都没有在主入口，都需要引其他文件。

2: 感谢回复

**Comment by huturen** [comment]
1: 将在下个补丁版本中在主入口导出

**Comment by huturen** [comment]
1： 已在 (1.8.4)[https://www.npmjs.com/package/http-request-mock/v/1.8.4] 版本中导出。
