### ISSUE TITLE
Cannot set property send of #<XMLHttpRequest> which has only a getter

### ISSUE THREAD

**Issue by xygengcn** [huturen/http-request-mock#12]
这个插件我是打算用来做chrome插件的，如果页面也同时对XMLHttpRequest的send重写就会出现这个报错，有什么好的解决方案吗

**Comment by huturen** [comment]
不太建议覆盖`XMLHttpRequest.send`方法，可能引入一些你不可控的问题。

如果实在要这样，可以尝试一下 `Object.defineProperty` 来修改send的getter。
