### ISSUE TITLE
Creating an interceptor rather than a mock

### ISSUE THREAD

**Issue by cristian-spiescu** [huturen/http-request-mock#13]
Hi,

I have several use cases for which I would like to intercept the original calls, do something, and then let the call continue it's normal life cycle.

As an example, for tests done in node.js, I would like to intercept the `set-cookie` header, store it as a global, and then enrich all subsequent calls w/ the received cookie.

I did a bit of browsing, but this use case doesn't seem to be possible. Am I correct?

**Comment by huturen** [comment]
Hi @cristian-spiescu 

**Case 1:** If you want to intercept calls and do something then let the call continue, you can try the feature of **"[Bypass](https://huturen.github.io/http-request-mock-docs/feature/bypass/)"**.

Example:
```javascript
mocker.mock({ 
    url: 'https://jsonplaceholder.typicode.com/photos/1',  
    body: function(req) {
        console.log('do something:', req); // do something on request info
        return this.bypass(); // let the call continue it's normal life cycle.
    }
});
```
<img width="844" alt="image" src="https://user-images.githubusercontent.com/5173298/215056232-252065c1-bd23-41a5-b81a-798962a3f500.png">


----

**Case 2:** If you want to intercept response headers, you can try the feature of **"[Remote mock data](https://huturen.github.io/http-request-mock-docs/feature/remote/)"**.

Example A:
```javascript
mocker.mock({ 
    url: 'https://jsonplaceholder.typicode.com/photos/1', 
    remote: 'https://jsonplaceholder.typicode.com/photos/1',
    body: function(remoteResponse, requestInfo) {
        console.log('response headers:', remoteResponse.headers); // get response headers
        return remoteResponse.responseText; 
    }
});
```
<img width="956" alt="image" src="https://user-images.githubusercontent.com/5173298/215070146-c30a2d11-9044-4f26-ab10-539f1c96784e.png">

**Note:**
Due to CORS restriction, you can't access all response headers. You can access only following standard response headers:

Cache-Control
Content-Language
Content-Type
Expires
Last-Modified
Pragma

So,  It's not possibile to intercept  `set-cookie` headers.

**Comment by cristian-spiescu** [comment]
Hi @huturen,

1/ Thanks for your detailed response. I must confess that, in my many years of work, I rarely seen such an informative and proactive answer to a question. 😄 

2/ I'm working in node.js. So there, I do have access to these headers. This is a quick and dirty piece of code that achieves what I described in my initial question. However, I would have rather used a specialized lib (such as this one), instead of having to maintain such code:

```js
    static receivedCookie: string;

    private inteceptRequestMethod() {
        // eslint-disable-next-line @typescript-eslint/no-this-alias
        const me = this;
        http.request = function (...args: unknown[]) {
            const result: ClientRequest = me.httpRequest.apply(null, args);
            if (NodeHttpAndHttpsRequestInterceptor.receivedCookie) {
                result.setHeader("Cookie", NodeHttpAndHttpsRequestInterceptor.receivedCookie);
            }
            result.on("response", data => {
                const setCookie = data.headers["set-cookie"];
                if (setCookie) {
                    NodeHttpAndHttpsRequestInterceptor.receivedCookie = Utils.substringBefore(setCookie[0], ";");
                }
            })
            return result;
        };
```

3/ Your **Case 1** doesn't help me in this case. However, your answer is valuable, because I have another use case, where this is the correct solution.

4/ Using **Case 1** works as expected. So the original call is correctly sent and received. Pity that I cannot access the headers. 

5/ **Case 2** doesn't work correctly. The request is not correctly forwarded. Here is what I do:

```js
mocker.mock({
    url: /.*/,
    remote: "http://localhost:8080/graphql",
    body: function(remoteResponse: any, requestInfo: any) {
        console.log("remoteResponse", remoteResponse);
        console.log("requestInfo", requestInfo)
        return remoteResponse.responseText; 
    }
})
```

Here is the output:

```
remoteResponse {
  status: 415,
  headers: {
    expires: '0',
    accept: 'application/json, application/graphql;charset=UTF-8, application/graphql, application/x-www-form-urlencoded;charset=UTF-8, application/x-www-form-urlencoded',
    'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
    'x-xss-protection': '1; mode=block',
    pragma: 'no-cache',
    'x-frame-options': 'SAMEORIGIN',
    date: 'Fri, 27 Jan 2023 17:33:15 GMT',
    connection: 'close',
    'x-content-type-options': 'nosniff',
    'content-type': 'application/json;charset=UTF-8'
  },
  response: {
    timestamp: '2023-01-27T17:33:15.486+0000',
    status: 415,
    error: 'Unsupported Media Type',
    message: 'Unsupported Media Type',
    path: '/graphql'
  },
  responseText: '{"timestamp":"2023-01-27T17:33:15.486+0000","status":415,"error":"Unsupported Media Type","message":"Unsupported Media Type","path":"/graphql"}',
  responseJson: {
    timestamp: '2023-01-27T17:33:15.486+0000',
    status: 415,
    error: 'Unsupported Media Type',
    message: 'Unsupported Media Type',
    path: '/graphql'
  }
}
requestInfo {
  url: 'http://localhost:8080/graphql',
  method: 'POST',
  query: { 'http://localhost:8080/graphql': '' },
  headers: {
    accept: '*/*',
    'content-type': 'application/json',
    'content-length': '385',
    'user-agent': 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)',
    'accept-encoding': 'gzip,deflate',
    connection: 'close'
  },
  body: '{"operationName":"login","variables":{"loginParams":{"username":"???","password":"???","rememberMe":false,"loginType":"STANDARD"}},"query":"mutation login($loginParams: LoginParamsInput!) {\\n  authService_login(loginParams: $loginParams) {\\n    status\\n    userDetails {\\n      username\\n      __typename\\n    }\\n    messageKey\\n    messageParams\\n    token\\n    __typename\\n  }\\n}\\n"}'
}
```
So the original content seems to be there, including "content type". But look at the response code (415 / Unsupported Media Type). And here is what the server says:

```
Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type '' not supported]
```

By looking at the code, I'd say that **Case 1** (which forwards the message correctly) uses line 234. And **Case 2** (w/ the above issue) uses line 212. 

![image](https://user-images.githubusercontent.com/4469897/215177188-5c726f7c-13ac-476b-a290-f794ff35a079.png)


6/ **Case 2** has another issue. I have to specify a constant remote url:

```js
mocker.mock({
    url: /.*/,
    remote: "http://localhost:8080/graphql",
```
But the interception expression captures all requests. A mechanism would be needed, so that I can somehow specify the original URL.

**Comment by huturen** [comment]
> 5/ Case 2 doesn't work correctly. The request is not correctly forwarded. Here is what I do

Thanks for your reminding, this is indeed a bug that `simpleRequest` should have carried request headers to the request of remote url. It may cause a 415 error in some content-type sensitive requests.

I will fix it in the next patched version.

----

> 6/ Case 2 has another issue. I have to specify a constant remote url

The **"remote"** feature is designed so that a matched mock request can use the results returned by another remote url.
It may not be suitable for your case, but there is a workaround to solve your problem:

```javascript
import axios from 'axios';
import httpAdapter from 'axios/lib/adapters/http';
import HttpRequestMock from '../src/index';

const mocker = HttpRequestMock.setupForUnitTest('node');
axios.defaults.adapter = httpAdapter; // do not use xhr adapter

mocker.mock({
  url: /.*/,
  body: async function(requestInfo) {
    if (requestInfo.url.includes('_mock_=yes')) return this.bypass(); // To avoid recursion

    const url = `${requestInfo.url}${requestInfo.url.includes('?') ? '&' : '?'}_mock_=yes`;
    const res = await axios.get(url);
    console.log('response headers:', res.headers);
    return res.data;
  }
});

it('custom response', async () => {
  const res = await axios.get('https://jsonplaceholder.typicode.com/photos/1');
  expect(res.status).toBe(200);
});
```
Unit test screen shot:
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/5173298/215267857-0ada618d-fc91-491d-b8e9-9b51a7e7e16a.png">

**Comment by huturen** [comment]
> 6/ Case 2 has another issue. I have to specify a constant remote url:
>
> mocker.mock({
>    url: /.*/,
>    remote: "http://localhost:8080/graphql",
> But the interception expression captures all requests. **A mechanism would be needed**, so that I can somehow specify the original URL.

As of version **_1.8.8_**, you can specify the original URL by `$url` which is matched by mock.
```javascript
mocker.mock({
  url: /.*/,
  remote: '$url', // $url points to the original URL which is matched by mock
  body: async function(remoteResponse, requestInfo) {
    console.log('request url:', requestInfo.url);
    console.log('response headers:', Object.keys(remoteResponse.headers).join(','));
    return remoteResponse.text;
  }
});

it('custom response', async () => {
  const res = await axios.get('https://jsonplaceholder.typicode.com/photos/1');
  expect(res.status).toBe(200);
  expect(res.headers['content-type']).toContain('application/json');
});
```

Unit test screen shot:
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/5173298/215314666-3c5d0256-9e14-4ccb-9e35-7764f63c13f9.png">

**Comment by cristian-spiescu** [comment]
> As of version 1.8.8, you can specify the original URL by $url which is matched by mock.

Wow. That's impressive. You fixed the 2 issues so quickly. However, I am realizing that I still cannot use **Case 2**:
* I can intercept the header `set-cookie`
* but then, for subsequent calls, I cannot inject `Cookie`. When the callback function is called, it's too late; the request to the server has already been made

> but there is a workaround to solve your problem

This is actually a neat idea! Use `http-request-mock` to do the interception. And then do the request the "classic" way. Here's what I've done:

```js
const initialRequestFunction = http.request;

const mocker = HttpRequestMock.setup();

let receivedCookie: string;

mocker.mock({
    url: /.*/,

    body: async function (req: any) {
        let result = "";
        return new Promise(resolve => {
            if (receivedCookie) {
                req.headers["Cookie"] = receivedCookie;
            }
            const newReq = initialRequestFunction(req.url, { method: req.method, headers: req.headers }, res => {
                const setCookie = res.headers["set-cookie"];
                if (setCookie) {
                    receivedCookie = Utils.substringBefore(setCookie[0], ";");
                }
                res.setEncoding('utf8');
                res.on('data', (chunk) => {
                    result += chunk;
                });
                res.on('end', () => {
                    resolve(result);
                });
            });
            newReq.write(req.body);
            newReq.end();
        });
    }
})
```

**Comment by huturen** [comment]
> Wow. That's impressive. You fixed the 2 issues so quickly. However, I am realizing that I still cannot use Case 2:
>
> I can intercept the header set-cookie
> but then, for subsequent calls, I cannot inject Cookie. When the callback function is called, it's too late; the request to the server has already been made

Update `http-request-mock` version to `1.8.10` and try the following codes:
```javascript
mocker.mock({
  url: /.*/,
  remote: '$url', // $url points to the original URL which is matched by mock
  requestHeaders: { 'cookie': 'cookie1=cookie-val-111; cookie2=xyz' }, // initial request headers
  body: async function(remoteResponse, requestInfo) {
    console.log('url:', requestInfo.url);
    // For subsequent calls, inject "Cookie" like this, you can custom it with remoteResponse.headers['set-cookie']
    this.requestHeaders['cookie'] = 'cookie1=cookie-val-222; cookie2=xyz';
    return remoteResponse.responseText;
  }
});
```
If it still couldn't solve your problem, use the workaround way mentioned above instead of `Case 2`.

**Comment by avivasyuta** [comment]
Hello. I need your help.

I'm trying to use your library to mock query responses. It is not clear to me how to return a mock response instead of the original one for fetch requests and for XMLHttpRequest at the same time. I tried returning a mock response via the response method, but this only works for fetch requests. For XMLHttpRequest the original response is returned.

I made an example [here](https://github.com/avivasyuta/interceptor-demo).

Could you show a suitable example for such a use case?

<img width="822" alt="Screenshot 2023-04-23 at 11 27 49" src="https://user-images.githubusercontent.com/15625379/233819972-42c5721b-bd51-4014-824c-242e5119b018.png">
