### ISSUE TITLE
Question: intercept request and response

### ISSUE THREAD

**Issue by chakatumi** [huturen/http-request-mock#14]
Hi,

Is there a way to intercept a request, make the original call and then intercept the response?

I saw that you can intercept the request, then make the original call or intercept the request. But can you do both? And I want to intercept any type of request,

**Comment by huturen** [comment]
Hi @chakatumi,

Yes, there are ways to intercept a request, make the original call, and then intercept the response.
Try the codes below: 
```javascript
// 1. define your mock configuration
mocker.mock({
  url: '//jsonplaceholder.typicode.com/', 
  remote: '$url', // $url points to the original URL which is matched by mock

  body: async function(remoteResponse, requestInfo) {
    console.log('original url:', requestInfo.url);
    console.log('response content:', remoteResponse.responseText);
      
    return { data: 'your fake data' };
  }
});
// 2. issue a request
axios
  .get('https://jsonplaceholder.typicode.com/photos/1?some=x')
  .then(res => console.log('photo', res.data))
```

![image](https://user-images.githubusercontent.com/5173298/224906458-7b952156-d353-46cc-ad2f-58c75596e69b.png)

**Comment by chakatumi** [comment]
I think I have not been clear enough. I want to intercept a request, do something, then make the original call and capture the response and do something again. 

In your example, it seems to me that you only intercept the response, but you call also see the original URL.

**Comment by huturen** [comment]
I think, the following codes may be what you want.
```javascript
// mock configuration
mocker.mock({
  url: '//jsonplaceholder.typicode.com/', 
  body: async function(requestInfo) {
    // 1. intercept a request
    const originalUrl = requestInfo.url;
      
    // 2. do something (here, output the original request information)
    console.log('original request info: ', requestInfo);
      
    // 3. then make the original call and capture the response 
    this.disable = 'YES'; // disable this mock to avoid recursion
    const res = await axios.get(requestInfo.url);
    this.disable = 'NO'; 
      
    // 4. and do something again (here, output the response)
    console.log('response content: ', res.data);
    return res.data;
  }
});

// issue a request
axios.get('https://jsonplaceholder.typicode.com/photos/1');
```
![image](https://user-images.githubusercontent.com/5173298/224987093-d14333c2-733c-4398-9e05-3d9841358508.png)

If the above codes is still not what you want, please let me know and show me your case.

**Comment by huturen** [comment]
I think, the following codes may be what you want.
```javascript
// mock configuration
mocker.mock({
  url: '//jsonplaceholder.typicode.com/', 
  body: async function(requestInfo) {
    // 1. intercept a request
    const originalUrl = requestInfo.url;
      
    // 2. do something (here, output the original request information)
    console.log('original request info: ', requestInfo);
      
    // 3. then make the original call and capture the response 
    this.disable = 'YES'; // disable this mock to avoid recursion
    const res = await axios.get(requestInfo.url);
    this.disable = 'NO'; 
      
    // 4. and do something again (here, output the response)
    console.log('response content: ', res.data);
    return res.data;
  }
});

// issue a request
axios.get('https://jsonplaceholder.typicode.com/photos/1');
```
![image](https://user-images.githubusercontent.com/5173298/224989338-bc0061c5-6834-4874-928e-4cc0836980a3.png)

If the above codes is still not what you want, please let me know and show me your case.

**Comment by cristian-spiescu** [comment]
A similar discussion was held in #13. @huturen made some modifs to support that use case. However, a pure interceptor is not possible.

We forked the project, and we'll propose a modification. In order to support such interception, 4 modifications need to be made. For:
* fetch
* XHR
* wx
* node

We'll first do the modif for fetch and ask the author if our proposal is OK. If yes, we'll propagate the modifs for the other cases as well.

NOTE: the above workaround may be OK for some use cases. But in our case, we need to be compatible w/ all the 4 methods above. Because the code may execute in all 4 modes
