### ISSUE TITLE
feature request: express style path `params`

### ISSUE THREAD

**Issue by reslear** [huturen/http-request-mock#18]
integrate dynamic routing using https://www.npmjs.com/package/path-to-regexp

for example:

before: 

```ts
mocker.get('/groups', (req) => {

  if (/groups\/./.test(req.url)) {
    const slug = req.url.match(/groups\/(.*?)$/)[1]
    return groups.find((group) => group.slug === slug)
  }

  return groups
})
```

after: 

```ts
mocker.get('/groups', groups)
  
mocker.get('/groups/:slug', ({ params }) => groups.find(({ slug }) => slug === params.slug))
```

also @huturen thx for good lib :)

**Comment by huturen** [comment]
hi @reslear

Obtaining the path information from the URL within a mock callback does not seem to be a commonly used scenario, and there are various alternative methods to accomplish it.

Additionally, implementing this particular feature would compromise the encapsulation of [RequestInfo](https://github.com/huturen/http-request-mock/blob/main/src/types.ts#L65), thus our current intention is not to support it.

**Comment by reslear** [comment]
well that's no problem, https://github.com/mswjs/msw seems to have it under the hood. Thanks anyway.
