### ISSUE TITLE
请求 mock 地址，axios 的 timeout 功能失效

### ISSUE THREAD

**Issue by TerryZ** [huturen/http-request-mock#23]
mock 了一个地址，并设置 delay 后，让这个响应在指定时间后才完成，例如，设置为 10000（10秒）

接着使用 axios

```js
axios.post('/some/api', undefined, { timeout: 1000 })
  .then(data => { console.log(data) })
  .catch(error => { console.log(error) })
```

调用该请求，10 秒后正常打印了 mock 的数据，而不是在 1 秒后，进入错误处理

使用一些在线的 mock 功能正常，可以进入错误处理

那么这个问题是不是无法解决？

**Comment by huturen** [comment]
@TerryZ 

版本[1.8.26](https://www.npmjs.com/package/http-request-mock/v/1.8.26) 已支持该特性。


单元测试：
![image](https://github.com/user-attachments/assets/64af1cfe-01bd-47af-9af4-6cc0958cec41)


浏览器验证效果：
<img width="598" alt="image" src="https://github.com/user-attachments/assets/a841a892-e31d-4c36-8bd1-4e20623273fb">

代码提交：
[关键代码](https://github.com/huturen/http-request-mock/commit/096d33f0f7d727f5fa62c7ea263a5ff035954a66#diff-b48b72abba1483b0ba646994423cf542022183575ff6628d2eebe43af90b200fR291)

**Comment by TerryZ** [comment]
可以，谢谢
