### ISSUE TITLE
[TypeScript] Fix typing of MockItemInfo and RequestInfo

### ISSUE THREAD

**Issue by eau-de-la-seine** [huturen/http-request-mock#26]
Hi Huturen,

Context: Without the correct typing I'm not able to explicitly use `RequestInfo` for `MockItemInfo.response` in TypeScript projects

---

Type to fix => `MockItemInfo`:
```ts
export interface MockItemInfo {
    url?: RegExp | string;
    method?: HttpVerb;
    requestHeaders?: Header;
    header?: Header;
    headers?: Header;
    delay?: number;
    body?: unknown;
    response?: unknown;
    remote?: string;
    status?: number;
    disable?: 'YES' | 'NO';
    times?: number;
    deProxy?: boolean;
}
```

Fix proposal for `MockItemInfo` (check `See here`):
```ts
export interface MockItemInfo {
    url?: RegExp | string;
    method?: HttpVerb;
    requestHeaders?: Header;
    header?: Header;
    headers?: Header;
    delay?: number;
    // See here
    body?: Object | string;
    // See here
    response?: (requestInfo: RequestInfo) => Promise<Object | undefined>;
    remote?: string;
    status?: number;
    disable?: 'YES' | 'NO';
    times?: number;
    deProxy?: boolean;
}
```

---

Type to fix => `RequestInfo`:
```ts
export interface RequestInfo {
    url: string;
    method: HttpVerb;
    query?: object;
    headers?: object;
    header?: object;
    body?: unknown;
    rawBody?: unknown;
    doOriginalCall?: () => Promise<OriginalResponse>;
}
```

Fix proposal for `RequestInfo` (check `See here`):
```ts
export interface RequestInfo {
    url: string;
    method: HttpVerb;
    // See here:
    query?: Query;
    // See here:
    headers?: Header;
    // See here: 
    header?: Header;
    // See here: 
    body?: string;
    // See here: what is rawBody? A `Buffer`?
    rawBody?: unknown;
    doOriginalCall?: () => Promise<OriginalResponse>;
}

// Note: the following types already exists but are not used...
export interface Query {
    [key: string]: string | string[];
}
export interface Header {
    [key: string]: string;
}
```

---

Notes:
* You should avoid using `any` or `unknown` or `object` when it's possible. It's not always possible to do that for the outputs, like the HTTP response from your API user, but it's possible to do that for the inputs (ex: `RequestInfo`)
* Breaking change proposal: It's really confusing to have `requestHeaders` AND `header` AND `headers`, you should just keep one which has the most "coherent" name and **use the same name for all of your types** like `MockItemInfo` AND `RequestInfo`
  * If you keep `headers`, which seems to be the most "coherent", you should rename `interface Header` => `interface Headers`

Thanks :)

**Comment by huturen** [comment]
@eau-de-la-seine 


I have just submitted a major change(a breaking change). Starting from version [2.0.1](https://www.npmjs.com/package/http-request-mock/v/2.0.1), the naming convention for headers has been standardized as per your proposal. The reason for having two separate header fields previously was primarily for backward compatibility. In this updated version, I have also added detailed comments in the production build files.

<img width="589" alt="image" src="https://github.com/user-attachments/assets/31e59df1-08eb-41de-a5f9-05afe9477e7a">

<img width="616" alt="image" src="https://github.com/user-attachments/assets/99bc9499-0583-4313-90bd-f635704d52a0">


Regarding the body and rawBody fields in RequestInfo, as explained in the following two links,
the post content can be a string, ArrayBuffer, Blob, DataView, File, FormData, TypedArray, URLSearchParams, Document, or null. Effectively, for us, this means the type is "unknown". Therefore, using `unknown` might be more appropriate.

[https://developer.mozilla.org/en-US/docs/Web/API/RequestInit#body](https://developer.mozilla.org/en-US/docs/Web/API/RequestInit#body)

[https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send)
