### ISSUE TITLE
[bug|feature?] http-request-mock does not support FormData

### ISSUE THREAD

**Issue by gokan-ekinci** [huturen/http-request-mock#27]
Hi huruten,

I am trying to send a [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData), you can see how it is used [here](https://stackoverflow.com/questions/47630163/axios-post-request-to-send-form-data) with axios.

So I have noticed that this:
```ts
    const { data } = await axios<AccessTokenOkResponse>({
      method: 'post',
      url: `${URL}/services/oauth2/token`,
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    });
``` 
... is NOT intercepted by `httpRequestMock.mock#body`

But this:
```ts
    const { data } = await axios<AccessTokenOkResponse>({
      method: 'post',
      url: `${URL}/services/oauth2/token`,
      headers: { 'Content-Type': 'multipart/form-data' },
      // data: formData, <= COMMENTED TO MAKE IT INTERCEPTED
    });
``` 
... is intercepted by `httpRequestMock.mock#body`

Maybe my mock is wrong?
```ts
      httpRequestMock.mock({
        url: `${URL}/services/oauth2/token`,
        method: 'post',
        status: 200,
        body: async (requestInfo: RequestInfo): Promise<unknown> => {
          console.log(`I am intercepted`);
          expect(requestInfo.headers).toEqual({ 'Content-Type': 'multipart/form-data' });
          return JSON.parse(fs.readFileSync('test/resources/access-token_response-ok.json', 'utf-8'));
        },
      });
```
... OR `http-request-mock#2.0.1` does not support `FormData`, in the second case could you make http-request-mock work with `FormData` ?

Thanks

**Comment by huturen** [comment]
It doesn't seem to be an issue with FormData. `http-request-mock@2.0.1` already supports FormData. It seems to be an issue with your unit tests. My unit tests are fine. Try removing the `expect` statement from your mock body function, it shouldn't be placed there.

<img width="684" alt="image" src="https://github.com/user-attachments/assets/af34ffe8-770a-4365-ab1d-3d5bf9c4a86f">

**Comment by gokan-ekinci** [comment]
Hi huturen, thanks for your answer, happy to know the lib supports `FormData` but I still have the issue.

It does not log **with or without** an `expect()` in `body`
* Not related to the current issue but when an `expect()` in `body` throws an exception, my tests freeze and time out. Is there a way to throw an exception immediately instead of time out with `http-request-body` ?

As you can see in my example the only difference was:
* There is no log with `data: formData`
* There is a log when `data: formData` is removed

Maybe it's related to my setup? I use `Ubuntu 24.04.1 LTS` and nodejs `v20.11.0`. I have also adapted this `FormData` test with an alternative wiremock library (`nock`) and it works with it

**Comment by huturen** [comment]
@gokan-ekinci 

I thoroughly analyzed the reason for the 'freeze.' It is because the exception in the mock body was not caught, so axios kept waiting for the mock response to return until it timed out, making it appear 'frozen.' I just released a new patch version， you can upgrade to version [2.0.2](https://www.npmjs.com/package/http-request-mock/v/2.0.2), which will make your unit tests work.

You can see my unit test below. When there is an exception in the mock body, it will now catch the exception and provide a warning log.
<img width="666" alt="image" src="https://github.com/user-attachments/assets/7c2929f3-4b4e-48de-82df-5e836f583926">
