### ISSUE TITLE
Should the bin/tmp.js be in the release?

### ISSUE THREAD

**Issue by mensfeld** [huturen/http-request-mock#5]
Hey,

I noticed, that there is a new file: https://my.diffend.io/npm/http-request-mock/1.6.8/1.6.9#d2h-095823 with a proxy server and references to https://jsonplaceholder.typicode.com.

I think it was added to the 1.6.9 by accident. Thanks

**Comment by huturen** [comment]
Yes, it was added by accident. It has been removed as of version 1.6.10.
