### ISSUE TITLE
Constraints on request headers and request body?

### ISSUE THREAD

**Issue by eau-de-la-seine** [huturen/http-request-mock#6]
Hello Huturen,

I was looking for a wiremock lib in NodeJS (for almost 2 hours), and I found your lib which looks really cool, but I was wondering:
```js
import HttpRequestMock from 'http-request-mock';
const mocker = HttpRequestMock.setup();

mocker.mock({
  // THIS IS THE HTTP REQUEST PART
  url: 'www.api.com/some-api' // or RegExp: /.*\/some-api$/
  method: 'get', // get, post, put, patch or delete
  delay: 0,

  // => request headers are missing
  // => request body is missing

  // THIS IS THE HTTP RESPONSE PART
  status: 200,
  header: { // respone headers
    'content-type': 'application/json',
    'some-header': 'value',
  },
  body: 'some response data'
});
```
I have done some tests, but I have noticed that your lib isn't strict about:
* URL query params. Ex: `http://localhost:12345?a=123&list=456&list=789` and `http://localhost:12345` should not be considered as the same thing. Currently, you cannot put a constraint on url query params.
* HTTP request headers. You cannot indicate what are the request headers. Sometimes you want to test if your request header includes your token etc
* HTTP request body. Sometimes you want to test if you're sending the correct HTTP request body

Example:
```js
mocker.mock({
  // THIS IS THE HTTP REQUEST PART
  request: {
    url: 'http://www.api.com/some-api?a=123&list=456&list=789', // <= Assert url query params
    method: 'get',
    headers: { // <= Assert HTTP request headers
      'content-type': 'application/json',
      'some-header': 'value',
    },
    body: {a: 'Hello World'}, // <= Assert HTTP request body
    delay: 0
  },

  // THIS IS THE HTTP RESPONSE PART
  response: {
    status: 200,
    headers: {
      'content-type': 'application/json',
      'some-header': 'value',
    },
    body: 'some response data'
  }
});
```

Good luck :+1:

**Comment by huturen** [comment]
hi eau-de-la-seine,

You can put some constraints on request headers and request body by dynamic-mocking, just like below:

![image](https://user-images.githubusercontent.com/5173298/178413384-8708b020-e80d-4cb7-84d7-8c4f8abe79d9.png)


## Demo code
```javascript
mocker.mock({
  // THIS IS THE HTTP REQUEST PART
  url: 'http://www.api.com/some-api?a=123&list=456&list=789', 
  method: 'post',
  delay: 0,

  // THIS IS THE HTTP RESPONSE PART
  status: 200,
  header: {
    'content-type': 'application/json',
    'some-header': 'value',
  },
  body: function(requestInfo) {
    console.log('request header: ', requestInfo.headers); // <= Assert HTTP request headers here
    console.log('request query: ', requestInfo.query); // <= Assert url query params here
    console.log('requets body: ', requestInfo.body); // <= Assert HTTP request body here
    return { data: 'some response data' };
  }
});


axios.post('http://www.api.com/some-api?a=123&list=456&list=789', { abc: 123, xyz: 456 }, {
  headers: { header1: 'val1' }
}).then(res => {
    console.log('post response headers: ', res.headers);
    console.log('post response body: ', res.data);
});
```

**Comment by huturen** [comment]
Take different logical branches by asserting url query params:

![image](https://user-images.githubusercontent.com/5173298/178415579-264450e1-8352-4909-9ae5-c86b37c7e853.png)


## Demo code
```javascript
mocker.mock({
  // THIS IS THE HTTP REQUEST PART
  url: 'http://www.api.com/some-api?a=123&list=456&list=789', 
  method: 'post',
  delay: 0,

  // THIS IS THE HTTP RESPONSE PART
  status: 200,
  header: {
    'content-type': 'application/json',
    'some-header': 'value',
  },
  body: function(requestInfo) {
    console.log('request header: ', requestInfo.headers); // <= Assert HTTP request headers here
    console.log('request query: ', requestInfo.query); // <= Assert url query params here
    console.log('requets body: ', requestInfo.body); // <= Assert HTTP request body here
    return { data: 'some response data' };
  }
});


axios.post('http://www.api.com/some-api?a=123&list=456&list=789', { abc: 123, xyz: 456 }, {
  headers: { header1: 'val1' }
}).then(res => {
    console.log('post response headers: ', res.headers);
    console.log('post response body: ', res.data);
});

```

**Comment by eau-de-la-seine** [comment]
Hello Huturen,

Thanks you very much for your very detailed response. I will do my asserts in the callback of `body` as you have suggested.

List for URL query params isn't supported yet. None of the following "standard" examples work (it always return one value):
* `https://jsonplaceholder.typicode.com/photos/1?list=a&list=b` 
* `https://jsonplaceholder.typicode.com/photos/1?list[]=a&list[]=b`
* `https://jsonplaceholder.typicode.com/photos/1?list[1]=a&list[0]=b`

Proposal: You should rename `header` into `headers` for consistency between the configuration object and the callback of `body`

Thank you, I consider this issue as closed

**Comment by huturen** [comment]
> List for URL query params isn't supported yet. None of the following "standard" examples work (it always return one value):
> 
> * `https://jsonplaceholder.typicode.com/photos/1?list=a&list=b`
> * `https://jsonplaceholder.typicode.com/photos/1?list[]=a&list[]=b`
> * `https://jsonplaceholder.typicode.com/photos/1?list[1]=a&list[0]=b`
> 
> Proposal: You should rename `header` into `headers` for consistency between the configuration object and the callback of `body`

Thanks for your proposal, the above features will be released in the next minor version, so stay tuned.

**Comment by huturen** [comment]
> List for URL query params isn't supported yet. None of the following "standard" examples work (it always return one value):
> 
> * `https://jsonplaceholder.typicode.com/photos/1?list=a&list=b`
> * `https://jsonplaceholder.typicode.com/photos/1?list[]=a&list[]=b`
> * `https://jsonplaceholder.typicode.com/photos/1?list[1]=a&list[0]=b`
> 
> Proposal: You should rename `header` into `headers` for consistency between the configuration object and the callback of `body`

The above features, as of Version 1.8.1, have been added.

![image](https://user-images.githubusercontent.com/5173298/180020958-819bf290-996d-44b4-9db1-61996f75e37d.png)
