### ISSUE TITLE
mockitem sort bring unpredictable mocks

### ISSUE THREAD

**Issue by llicour** [huturen/http-request-mock#7]
Hi
Implementing a specific mock regexp for catchall, i experienced some other mock that where not used by mock engine. Digging code, i found a sort based on url size (https://github.com/huturen/http-request-mock/blob/main/src/mocker/mocker.ts#L339) that reorder mockitem in a way that doesn't fit code inital order (and logic)

In the following code, 2nd mockitem (catchall) is reorder at the 1st place as url size is bigger. So 1st mockitem is never used
```
    mocker.post('https://example.com', 'mocked');
    mocker.mock({
      url: /^(?!http:\/\/127\.0\.0\.1:\d+\/).*/, // mock all but localhost loopback
      status: 599,
      response(req: any) {
        console.info(req);
        throw Error(`unmocked url ${req.method} ${req.url}`);
      },
    });
```

For this used case, i change my code, but i think that sorting mockitem sould be removed to let code decide evaluation order

**Comment by huturen** [comment]
Hi @llicour 

The sort based on URL length is for the purpose of distinguishing some URLs with the same prefix, such as:
`http://test.com/abc`
`http://test.com/abc/xyz/123`
Thus, the both urls above can be mocked by the sort.

I'm considering to remove the sort in the next minor version, as it's not suitable for your case that you mentioned above.

**Comment by huturen** [comment]
The sort based on url length has been removed since version [`1.8.3`](https://www.npmjs.com/package/http-request-mock/v/1.8.3).
Now, mock is based on the insertion order instead of url length.
